name: Release

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Unit-test:
    name: Run tests and release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
          {java-version: 1.8}
      - name: Test and release
        run: |
          ./gradlew clean
          ./gradlew test
